import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Matthew Cheng | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10">
        <section className="bg-white min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Matthew Cheng</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl"/>
              </li>
              <li>
                <a className="bg-gradient-to-tr from-cyan-500 to-purple-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a>
              </li>
            </ul>
          </nav>
          
        </section>
      </main>
    </div>
  )
}
